# ---- MongoDB ----

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017

---

# ---- Node.js App ----

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qinter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qinter
  template:
    metadata:
      labels:
        app: qinter
    spec:
      containers:
        - name: qinter
          image: qinter:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DATA_SOURCE
              value: "mongo"
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/backend-database"

---

apiVersion: v1
kind: Service
metadata:
  name: qinter-service
spec:
  selector:
    app: qinter
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
